# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - Top10GITHUB

on:
  push:
    branches:
      - clean_branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Prepare deployment package
        run: |
          # Create deployment directory
          mkdir -p deploy
          
          # First, let's see what was built
          echo "Build output structure:"
          ls -la .next/
          echo "Standalone directory:"
          ls -la .next/standalone/ || echo "No standalone directory found"
          
          # Copy standalone build output
          if [ -d ".next/standalone" ]; then
            cp -r .next/standalone/* deploy/
          else
            echo "No standalone build found, copying full .next directory"
            mkdir -p deploy
            cp -r .next deploy/.next
          fi
          
          # Copy static files if they exist
          if [ -d ".next/static" ]; then
            mkdir -p deploy/.next
            cp -r .next/static deploy/.next/static
          fi
          
          # Copy public directory if it exists
          if [ -d "public" ]; then
            cp -r public deploy/public
          fi
          
          # Copy package.json for Azure to understand the project  
          cp package.json deploy/
          
          # Verify package.json content
          echo "Checking package.json start script:"
          grep '"start":' deploy/package.json
          
          # Debug: List what was copied
          echo "Contents of deploy directory:"
          ls -la deploy/
          echo "Contents of deploy/.next (if exists):"
          ls -la deploy/.next/ || echo "No .next directory in deploy"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Top10GITHUB'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D957C550078B4BE7A33EB6694A8F5FD8 }}