name: Deploy Next.js (standalone) to Azure Web App - top10webapp

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build Next.js (standalone)
        run: npm run build

      # 准备部署内容：仅包含 standalone 运行所需文件
      - name: Prepare deploy folder
        run: |
          rm -rf deploy
          mkdir -p deploy/.next
          cp -r .next/standalone/* deploy/
          cp -r .next/static deploy/.next/static
          if [ -d public ]; then cp -r public deploy/public; fi
          cat > deploy/package.json <<'EOF'
          {
            "name": "next-standalone",
            "private": true,
            "scripts": {
              "start": "node server.js"
            }
          }
          EOF

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'top10webapp'   # 替换为你的 Web App 名称
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ./deploy
